# Generated by Django 5.1.2 on 2024-10-28 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_icon', models.CharField(choices=[('shopping', 'Shopping'), ('food', 'Food'), ('transport', 'Transport'), ('salary', 'Salary')], default='shopping', max_length=20)),
                ('transaction_title', models.CharField(max_length=200)),
                ('transaction_detail', models.TextField()),
                ('transaction_type', models.CharField(choices=[('E', 'Expense'), ('R', 'Revenue')], max_length=1)),
                ('transaction_price', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_title'], name='transaction_title_index')],
            },
        ),
    ]
