# Generated by Django 5.1.2 on 2024-10-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transactions_transaction_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('event_icon', models.CharField(choices=[('date', 'Date'), ('card', 'Card'), ('maik', 'Mail'), ('notification', 'Notification')], max_length=20)),
            ],
        ),
    ]
