# Generated by Django 5.1.2 on 2024-10-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reminder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
