# Generated by Django 5.1.2 on 2024-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reminder_user_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_icon',
            field=models.CharField(choices=[('event', 'Event'), ('shopping', 'Shopping'), ('mail', 'Mail'), ('notification', 'Notification')], default='shopping', max_length=20),
        ),
    ]
