# Generated by Django 5.1.2 on 2024-11-04 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transaction_transaction_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='event_icon',
            field=models.CharField(choices=[('date', 'Date'), ('card', 'Card'), ('mail', 'Mail'), ('notification', 'Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_icon',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('food', 'Food'), ('transport', 'Transport'), ('salary', 'Salary')], default='shopping', max_length=20),
        ),
    ]
