# Generated by Django 5.1.2 on 2024-11-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reminder_event_icon_alter_reminder_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='event_date',
            new_name='reminder_date',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='event_icon',
            new_name='reminder_icon',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='event_title',
            new_name='reminder_title',
        ),
    ]
