# Generated by Django 5.0.1 on 2024-11-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_reminder_options_reminder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_icon',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('salary', 'Salary')], default='shopping', max_length=20),
        ),
    ]
